### ISSUE TITLE
JATS representation on paywall subcommittee

### ISSUE THREAD

**Issue by jmcmurry** [jmcmurry/RRID-TS#10]
@Melissa37 on the call you mentioned being able to find a suitable other technical rep for JATS on the subcommittee; that would be great, thanks :)

**Comment by Melissa37** [comment]
Hi there

I don't think I can persuade anyone from the JATS committee to join this group, but I chair JATS4R and have contacts with them so I will be able to discuss with them some ideas and recommendations I put forward for tagging.
